language: node_js
branches:
    only:
        - master
env:
    global:
        # GH_OAUTH_TOKEN is the oauth token generated as described at
        # https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
        #
        # curl -u 'username' -d '{"scopes":["repo"],"note":"push to gh-pages from travis"}' https://api.github.com/authorizations
        #
        # It must be encrypted using the travis gem
        # http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
        #
        # travis encrypt GH_OAUTH_TOKEN=XXXXXXXXXXXXXXX
        #
        # User specific env variables
        - secure: "g53iWltpe20zykrdF3CIrV6lBovLS+/jlhrOR8BFmUwcgo1/RNgYirntV2qNvgjZooguEpesELK4PqTdHfUaanRR1zwrY6RP9VyQI1iFD7Jq9HmzNdpg06vQNh97b5CEvc6/TXh6xlRYf+6MPV9Lwe1tYRwT3mLMlJ5wSOYP7DA="
        - GH_OWNER: andyli
        - GH_PROJECT_NAME: VideoGame_History_Industry_Society_and_Creativity
        # This .travis.yml file instructs travis-ci.org to build your master branch using `yeoman build`
        # and deploy the output to your project's gh-pages branch.

before_script:
    - gem update --system
    - gem install sass -v 3.2.13
    - gem install compass -v 0.12.2
    - npm install -g grunt-cli bower
script:
    # We want to gate on passing tests and a successful build
    - bower install
    - grunt
after_success:
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
    - cd site
    - if git checkout gh-pages; then git checkout -b gh-pages; fi
    - git rm -r .
    - cp -R ../dist/* .
    - cp ../dist/.* .
    - git add -f .
    - git config user.email "andy@onthewings.net"
    - git config user.name "Andy Li"
    - git commit -am "adding the yeoman build files to gh-pages [ci skip]"
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
